remote_theme: mmistakes/minimal-mistakes@4.16.6

title: WeatherLink v2 API

url: "https://weatherlink.github.io"
baseurl: /v2-api

search: false

after_footer_scripts:
  - /assets/vendor/weatherlink/js/author.js
  - /assets/vendor/weatherlink/js/footer-copyright.js
  - /assets/vendor/weatherlink/js/api-test-tool.js

include:
  - _pages

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "navMain"

plugins:
  - jekyll-include-cache
